version: '3'
services:
  nginx:
    build:
      context: ./nginx  # The path to the directory containing your Nginx Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - flask

  flask:
    build:
      context: ./flask  # The path to the directory containing your Flask Dockerfile
    container_name: flask
    volumes:
      - ./flask:/app
    ports:
      - "5000:5000"

